# Generated by Django 5.2.5 on 2026-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user_type'], name='useracct_user_type_idx'),
        ),
    ]
