[project]
name = "jobapp"
version = "0.1.0"
description = "Job Board REST API built on Django + DRF"
readme = "Readme.md"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25.1.0",
    "django>=5.2.13,<6",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "drf-spectacular>=0.29.0",
    "psycopg2-binary==2.9.10",
    "pyjwt>=2.12.0",
    "python-dotenv>=1.2.2",
]

[tool.uv]
package = false
