# Generated by Django 5.2.5 on 2025-09-26 05:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_stream_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["business_stream_name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("profile_description", models.TextField(blank=True)),
                ("company_website_url", models.URLField(blank=True, max_length=500)),
                ("contact_email", models.EmailField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.businessstream",
                    ),
                ),
                (
                    "user_account",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "company"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyImages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
