# Generated by Django 5.2.5 on 2026-04-24 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='company_status_idx'),
        ),
    ]
