# Generated by Django 5.2.5 on 2026-04-24 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_status_idx'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='joblocation',
            index=models.Index(fields=['country', 'city'], name='joblocation_country_city_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_published', 'is_active', '-created_at'], name='jobpost_pub_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['company', '-created_at'], name='jobpost_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['deadline_date'], name='jobpost_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpostactivity',
            index=models.Index(fields=['job_post', 'application_status'], name='jpactivity_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpostactivity',
            index=models.Index(fields=['user_account', '-application_date'], name='jpactivity_user_date_idx'),
        ),
    ]
