# Generated by Django 5.2.5 on 2026-04-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_status_idx'),
        ('jobs', '0002_joblocation_joblocation_country_city_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_min__lte', models.F('salary_max')), _connector='OR'), name='jobpost_salary_min_le_max'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('salary_min__isnull', True), ('salary_min__gte', 0), _connector='OR'), models.Q(('salary_max__isnull', True), ('salary_max__gte', 0), _connector='OR')), name='jobpost_salary_non_negative'),
        ),
    ]
