# Generated by Django 5.1.6 on 2025-02-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('IN_PROGRESS', 'In Progress')], default='OPEN', max_length=11),
        ),
    ]
