# Generated by Django 5.1.6 on 2025-02-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYER', 'Employer'), ('FREELANCER', 'Freelancer'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
