# Generated by Django 5.2.5 on 2026-04-24 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='educationdata',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), models.Q(('percentage__gte', 0), ('percentage__lte', 100)), _connector='OR'), name='education_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='educationdata',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='education_date_order'),
        ),
        migrations.AddConstraint(
            model_name='experiencedata',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='experience_date_order'),
        ),
    ]
