# Generated by Django 5.2.16 on 2026-08-01 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('jobs', '0003_jobpost_jobpost_salary_min_le_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', models.JSONField(default=dict)),
                ('applicant_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_reports', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_post', '-created_at'], name='screening_job_created_idx')],
            },
        ),
    ]
